#!/usr/bin/env python3
"""
Third Stage: Graphyne Cluster Processor                                                     
                                                                                            
This script processes a large set of XYZ files generated by the first script.     
   The following tasks perfoms:                                                             
   1. Reads carbon cluster structures from XYZ files.                                           
   2. Converts atomic coordinates into RDKit molecule objects using distance-based 
      bond perception with chemically informed cutoffs                                 
   3. Adds implicit hydrogens based on valence rules.                                           
   4. Computes InChIKey, aromatic SMILES, and Kekule SMILES for each structure.                 
   5. Uses multiprocessing to handle large numbers of files efficiently.                        
   6. Removes duplicate structures based on InChIKey.                                           
   7. Saves unique structures with standardized naming and generates summary reports.           
      Important: selection of the representative structure from each duplicate group using the 
      smallest cluster ID for consistency with input numbering.                                                                                         

"""

import os
import glob
import numpy as np
from collections import defaultdict
from rdkit import Chem
from rdkit.Chem.rdchem import BondType
from rdkit.Chem.inchi import MolToInchiKey
from pathlib import Path
import re
import multiprocessing as mp
import csv
from tqdm import tqdm
import argparse

# ----------------------- PARAMETERS ------------------------- #

# Distance cutoffs used for bond perception from coordinates
BOND_CUTOFF = 1.60      # Maximum distance to consider any bond between carbons
TRIPLE_CUTOFF = 1.28    # Upper distance limit for triple bonds
AROMATIC_MIN = 1.32     # Lower distance limit for aromatic bonds

# Multiprocessing settings
CHUNKSIZE = 250         # Number of tasks per chunk sent to each worker


# --------------------- CLI HANDLING --------------------- #
def parse_arguments():
    parser = argparse.ArgumentParser(description="Process graphyne carbon clusters and remove duplicates.")
    parser.add_argument("-i", "--input-dir", default="triangle_clusters_all",
                        help="Input directory containing cluster_*.xyz files")
    parser.add_argument("-o", "--output-dir", default=None,
                        help="Base output directory (unique_clusters, CSVs, etc. will be written here)")
    parser.add_argument("-c", "--cpu", type=int, default=1,
                        help="Number of CPU cores to use")
    return parser.parse_args()


# --------------------- HELPER FUNCTIONS --------------------- #
def init_worker():
    """
    Initialize multiprocessing worker processes.
    Configures signal handling to ignore SIGINT (KeyboardInterrupt) in child processes.
    """
    import signal
    signal.signal(signal.SIGINT, signal.SIG_IGN)


def read_xyz(filename: str):
    """
    Read an XYZ file and return atomic coordinates as a numpy array,
    the metadata line, and any additional lines at the end of the file.
    Only carbon atoms are expected in these files.   
    """
    with open(filename, "r") as f:
        lines = f.readlines()

    n_atoms = int(lines[0].strip())
    metadata = lines[1].strip() if len(lines) > 1 else ""

    coords = []
    i = 2
    count = 0
    while i < len(lines) and count < n_atoms:
        parts = lines[i].split()
        if len(parts) >= 4:
            try:
                coords.append(list(map(float, parts[1:4])))
                count += 1
            except ValueError:
                pass
        i += 1

    tail = [line.rstrip("\n") for line in lines[i:]]
    return np.array(coords, dtype=float), metadata, tail


def extract_triangle_count(metadata: str) -> int:
    """
    Extract the number of triangle units from the comment/metadata line of each XYZ file.
    """
    match = re.search(r'triangles\s*\[([^\]]+)\]', metadata)
    if match:
        items = match.group(1).split(',')
        return len([x for x in items if x.strip()])
    return 0


# --------------------- MOLECULE CONSTRUCTION --------------------- #
def coords_to_mol(coords):
    """
    Convert a set of carbon coordinates into an RDKit molecule object.
    Bonds are created based on interatomic distances using predefined cutoffs.
    """
    n = len(coords)
    mol = Chem.RWMol()

    # Add carbon atoms
    for _ in range(n):
        mol.AddAtom(Chem.Atom(6))

    # Add bonds based on distance
    for i in range(n):
        for j in range(i + 1, n):
            d = np.linalg.norm(coords[i] - coords[j])
            if 1.05 < d < BOND_CUTOFF:
                if d < TRIPLE_CUTOFF:
                    mol.AddBond(i, j, BondType.TRIPLE)
                elif d > AROMATIC_MIN:
                    mol.AddBond(i, j, BondType.AROMATIC)
                else:
                    mol.AddBond(i, j, BondType.SINGLE)
    return mol


def add_hydrogens_fast(mol):
    """
    Custom valence-driven hydrogen addition optimized for graphyne structures.  
    Avoids RDKit's generic AddHs() to provide finer control over fractional 
    aromatic valences and mixed hybridization states common in graphyne-like structures.
    """
    mol = Chem.RWMol(mol)
    atoms = list(mol.GetAtoms())

    for atom in atoms:
        if atom.GetSymbol() != "C":
            continue

        val = 0.0
        for b in atom.GetBonds():
            bt = b.GetBondType()
            if bt == BondType.SINGLE:
                val += 1
            elif bt == BondType.DOUBLE:
                val += 2
            elif bt == BondType.TRIPLE:
                val += 3
            elif bt == BondType.AROMATIC:
                val += 1.5

        need = int(round(4.0 - val))
        if 0 < need <= 2:
            idx = atom.GetIdx()
            for _ in range(need):
                h = mol.AddAtom(Chem.Atom("H"))
                mol.AddBond(idx, h, BondType.SINGLE)

    return mol.GetMol()


# --------------------- WORKER FUNCTION --------------------- #
def process_file(filename):
    """
    Process a single XYZ file:
    1. Read coordinates
    2. Build RDKit molecule
    3. Add hydrogens
    4. Sanitize and generate InChIKey + SMILES strings
    Returns only lightweight data.
    """
    coords, metadata, _ = read_xyz(filename)

    mol = coords_to_mol(coords)
    mol = add_hydrogens_fast(mol)

    try:
        Chem.SanitizeMol(mol)
    except Exception:
        pass

    try:
        inchi = MolToInchiKey(mol)
    except Exception:
        inchi = "FAILED_INCHI"

    try:
        aro = Chem.MolToSmiles(mol, kekuleSmiles=False)
    except Exception:
        aro = "FAILED_SMILES"

    try:
        kek = Chem.MolToSmiles(mol, kekuleSmiles=True)
    except Exception:
        kek = "FAILED_SMILES"

    return inchi, filename, aro, kek, metadata


# --------------------- UTILITY --------------------- #
def get_cluster_id(filename):
    """Extract cluster number for consistent duplicate selection."""
    m = re.search(r'cluster_(\d+)', os.path.basename(filename))
    return (int(m.group(1)) if m else 10**12, filename)


# --------------------- MAIN PROCESSING -------------------- #
def main(input_dir="triangle_clusters_all", output_dir=None, n_cpu=1):
    """
    Main execution function with output directory support.
    Deduplication order follows first-encountered InChIKey. Within each duplicate group, 
    the structure with the smallest cluster ID is chosen as the representative.

    """                                                                                                                                      
    
    if output_dir is None:
        base = Path(os.getcwd())
    else:
        base = Path(os.path.abspath(output_dir))
    
    base.mkdir(parents=True, exist_ok=True)

    input_folder = Path(input_dir)
    if not input_folder.is_absolute():
        # If relative, try relative to current working dir first
        input_folder = Path(os.path.abspath(input_dir))

    output_unique_dir = base / "unique_clusters"
    output_unique_dir.mkdir(exist_ok=True)

    # Find input files
    files = sorted(glob.glob(str(input_folder / "cluster_*.xyz")))
    if not files:
        print(f"ERROR: No cluster_*.xyz files found in {input_folder}")
        return

    print(f"Found {len(files)} XYZ files in {input_folder}")
    print(f"Using {n_cpu} CPU core(s)")
    print(f"Output directory: {base}\n")

    # ---------------- PARALLEL PROCESSING ---------------- #
    inchi_map = defaultdict(list)
    smiles_dict = {}   # filename -> (aromatic, kekule, metadata)

    ctx = mp.get_context("spawn")
    with ctx.Pool(processes=n_cpu, initializer=init_worker) as pool:
        for inchi, fn, aro, kek, meta in tqdm(
            pool.imap_unordered(process_file, files, chunksize=CHUNKSIZE),
            total=len(files),
            desc="Processing structures"
        ):
            inchi_map[inchi].append(fn)
            smiles_dict[fn] = (aro, kek, meta)

    # ---------------- DEDUPLICATION ---------------- #
    # Keep the structure with the smallest cluster ID for each unique InChIKey
    unique = {
        k: min(v, key=get_cluster_id)
        for k, v in inchi_map.items()
    }

    # ---------------- OUTPUT FILES ---------------- #
    summary_path = base / "Structures_summary.csv"
    aro_path = base / "SMILES_Aromatic.csv"
    kek_path = base / "SMILES_Kekule.csv"

    with open(summary_path, "w", newline="") as summary, \
         open(aro_path, "w") as aro_out, \
         open(kek_path, "w") as kek_out:

        writer = csv.writer(summary)
        writer.writerow(["Structure", "Num_Triangles", "Aromatic_SMILES",
                         "Kekule_SMILES", "InChIKey"])

        for inchi, ref in tqdm(unique.items(), desc="Writing unique structures"):
            coords, meta, tail = read_xyz(ref)
            aro, kek, _ = smiles_dict[ref]

            n_atoms = len(coords)
            tri = extract_triangle_count(meta)

            # Extract number for naming
            match = re.search(r'cluster_(\d+)', os.path.basename(ref))
            num = match.group(1) if match else "000000"

            # Summary
            writer.writerow([os.path.basename(ref), tri, aro, kek, inchi])

            # SMILES
            aro_out.write(aro + "\n")
            kek_out.write(kek + "\n")

            # Save unique XYZ
            out_xyz = output_unique_dir / f"unique_{num}_{n_atoms}atoms.xyz"
            with open(out_xyz, "w") as f:
                f.write(f"{n_atoms}\n")
                f.write(f"{meta}\n")
                for x, y, z in coords:
                    f.write(f"C {x:.6f} {y:.6f} {z:.6f}\n")
                if tail:
                    f.write("\n".join(tail) + "\n")

    print(f"\nProcessing complete! Unique structures: {len(unique)}")
    print(f"Unique clusters saved to: {output_unique_dir}")
    print(f"Summary files written to: {base}")


# --------------------- ENTRY POINT --------------------- #
if __name__ == "__main__":
    args = parse_arguments()
    main(
        input_dir=args.input_dir,
        output_dir=args.output_dir,
        n_cpu=max(1, args.cpu)
    )
